### ISSUE TITLE
Ignore/remove .DS_Store files

### ISSUE THREAD

**Issue by cstephen** [ua-snap/epa-justice#19]
This is a very common issue when using git on a Mac, but to remove stray/irrelevant `.DS_Store` files from a git repo retroactively, you can do this:

Create a new file in the root directory of the repo called `.gitignore` with this content:

```
.DS_Store
```

Then, run the following commands to add and apply `.gitignore` retroactively:

```
git add .gitignore
git rm -r --cached .
git add .
git commit -a -m 'Ignore .DS_Store files retroactively.'
```

**Comment by Joshdpaul** [comment]
closed by https://github.com/ua-snap/epa-justice/commit/460778337e670c923211eb31e6a522982b9003fd
